# Generated by Django 3.0.3 on 2020-03-10 09:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0003_auto_20200310_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='createdDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
