# Generated by Django 3.0.3 on 2020-03-10 09:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0004_auto_20200310_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='createdDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
