# Generated by Django 3.0.3 on 2020-03-10 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0005_auto_20200310_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='dislikeCount',
        ),
    ]
