# Generated by Django 3.0.4 on 2020-04-06 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0011_auto_20200328_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='link',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
