# Generated by Django 3.0.4 on 2020-04-12 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0014_eventvote_saved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventvote',
            name='saved',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
