# Generated by Django 3.0.4 on 2020-05-08 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0015_auto_20200412_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='bodyText',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
